version: "3"
services:
  mongodb:
    image: 'mongo'
    container_name: 'todo-mongodb'
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - "27017:27017"
  server:
    container_name: 'todo-server'
    build: .
    command: >
      sh -c "npm install && npm start"
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - PORT=8000
      - MONGO_DB=development
      - MONGO_PORT=27017
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    links:
      - mongodb
