version: "3"
services:
  mongodb:
    image: 'mongo'
    container_name: 'todo-mongodb'
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - "27017:27017"
  server:
    image: 'opuso/server'
    ports:
      - "8080:8080"
