version: "3"
services:
  mongodb:
    image: 'mongo'
    container_name: 'mongo'
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - "1000:27017"
  server:
    container_name: 'opuso-server'
    build: .
    command: >
      sh -c "npm install && npm start"
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - PORT=4000
      - MONGO_URI=mongodb://mongodb:27017/development
      - APP_SECRET=secretkeyhehe
    ports:
      - "4000:4000"
    depends_on:
      - mongodb
    links:
      - mongodb
